# ===============================
# RegenFlix - Configuração Netlify
# ===============================

[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_PUBLIC_SUPABASE_URL = "https://tpmiatandpidzkefneof.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
BUN_VERSION = "1.1.20"
NODE_VERSION = "18.20.3"
SECRETS_SCAN_ENABLED = "false"
